### PR TITLE
Remove creation of Microphysics as a CMake library 

### PR DESCRIPTION
**Pull request by psharda**
We do not need to create Microphysics as a library while compiling it with CMake. This became redundant after we modified CMakeLists to just build the primordial chem target directly.

This will help build Microphysics on Setonix (for Quokka).

Fixes https://github.com/AMReX-Astro/Microphysics/issues/1185.

### CODE REVIEW

**Comment by BenWibking** [comment]
This should fix https://github.com/AMReX-Astro/Microphysics/issues/1185.

**Comment by BenWibking** [comment]
I can build successfully on Setonix, but the test crashes and burns when run on CPU:

```
DVODE: corrector convergence failed repeatedly or with abs(H) = HMIN
[ERROR] integration failed in net
istate = -5
zone = (11603832, 0, 1)
time = 0
dt = 160214.9111706569
temp start = 10
xn start = 1.823018216771485e+17 3.64603643354297e+16 3.64603643354297e+16 3.646036433542971e+16 3.64603643354297e+16 3.64603643354297e+16 3.646036433542973e+16 3.646036433542972e+16 3.64603643354297e+16 3.646036433542971e+16 3.646036433542971e+16 3.64603643354297e+16 3.64603643354297e+16 3.64603643354297e+16
dens current = 1.891131659668635e-06
temp current = nan
xn current = 0.07142857142857142 0.07142857142857142 0.07142857142857141 0.07142857142857142 0.07142857142857142 0.07142857142857142 0.07142857142857142 0.07142857142857142 0.07142857142857141 0.07142857142857142 0.07142857142857142 0.07142857142857142 0.07142857142857141 0.07142857142857141
energy generated = 0
------------------------------------
successful? 0
------------------------------------
T initial = 100
T final =   10
Eint initial = 22899962017633.87
Eint final =   831176669.4826175
rho initial = 9.109381880000001e-28
rho final =   1.891131659668635e-06
------------------------------------
New number densities:
1.823018216771485e+17
3.64603643354297e+16
3.64603643354297e+16
3.64603643354297e+16
3.64603643354297e+16
3.64603643354297e+16
3.646036433542972e+16
3.646036433542972e+16
3.64603643354297e+16
3.646036433542971e+16
3.64603643354297e+16
3.64603643354297e+16
3.64603643354297e+16
3.64603643354297e+16
AMReX (23.06-23-g02ac1f39bce4) finalized
```

**Comment by BenWibking** [comment]
Ah ok, it works if I specify the input file on the command line. But this is a bug -- it should refuse to run if no input file is specified.

**Review by BenWibking — APPROVED** [review]
This fixes the build issue and works on Setonix, so I approve.

**Comment by BenWibking** [comment]
I am getting errors such as:
```
/opt/rocm/hip/include/hip/amd_detail/texture_fetch_functions.h:143:5: error: unused variable 's' [-Werror,-Wunused-variable]
```

Somehow `-Werror` is getting turned on for this build, but I specified
```
cmake .. -DBUILD_UNIT_TEST=ON -DBUILD_AMREX=ON -DAMReX_GPU_BACKEND=HIP
```
when configuring...

**Comment by BenWibking** [comment]
Ah, this was my fault. We need to get rid of this line:
https://github.com/AMReX-Astro/Microphysics/blob/bcf06921ae6144e0f1d24ceb8181af43357e9f84/CMakeLists.txt#L114

and instead just set `CXXFLAGS=-Werror` when doing the CI tests.

**Comment by psharda** [comment]
> Ah, this was my fault. We need to get rid of this line:
> 
> https://github.com/AMReX-Astro/Microphysics/blob/bcf06921ae6144e0f1d24ceb8181af43357e9f84/CMakeLists.txt#L114
> 
> and instead just set `CXXFLAGS="-Werror -Wall -Wextra"` when doing the CI tests.

I didn't follow how we just set `CXXFLAGS="-Werror -Wall -Wextra"` only for CI tests?

**Comment by BenWibking** [comment]
> > Ah, this was my fault. We need to get rid of this line:
> > https://github.com/AMReX-Astro/Microphysics/blob/bcf06921ae6144e0f1d24ceb8181af43357e9f84/CMakeLists.txt#L114
> > 
> > and instead just set `CXXFLAGS="-Werror -Wall -Wextra"` when doing the CI tests.
> 
> I didn't follow how we just set `CXXFLAGS="-Werror -Wall -Wextra"` only for CI tests?

We can add something like this to the .yml file:
https://github.com/AMReX-Codes/amrex/blob/d28b9ab1cd64e648372ae679a6be01c733899525/.github/workflows/hip.yml#L37

**Comment by BenWibking** [comment]
This PR looks fine to me. The warnings could be fixed in another PR that moves the flags from CMakeLists.txt to the .yml file.

**Review by zingale — APPROVED** [review]

**Pull request merged**
