### PR TITLE
modify the SDC+NSE update to not include the advective part in enuc

### PR DESCRIPTION
**Pull request by zingale**
This removes the advection component from rho (B/A) and computes the energy update as:

[rho (B/A)]^{n+1} - [rho (B/A)]^n

this has it differing from #1090, which does something like:

rho^{n+1/2} [ (B/A)^{n+1} - (B/A)^n ]

### CODE REVIEW

**Comment by zingale** [comment]
okay, I think that this is definitely the correct thing to do.  Here's `nse_test` run with `convergence_simplified_sdc_w_vel.sh` -- this puts a uniform diagonal velocity field (still very subsonic) in the domain and advects as the NSE pulse evolves.

Here's the 128^2 run on `development`:

nse_test_128_plt00250_development_slice

and here it is with this PR:

nse_test_128_plt00250_slice

**Comment by zingale** [comment]
also, here's the convergence on development:

```
density                         2.464513e+20   0.500      1.743019e+20   -0.420      2.331303e+20
xmom                            9.647833e+28   0.295      7.861733e+28   -0.146      8.698512e+28
ymom                            9.647792e+28   0.294      7.871771e+28   -0.143       8.69222e+28
rho_E                           1.355699e+39   -0.136      1.489638e+39   0.385      1.140902e+39
rho_e                           1.356198e+39   -0.136      1.490024e+39   0.382      1.143697e+39
Temp                            3.668486e+22   0.026      3.603456e+22   0.218      3.097427e+22
rho_H1                          2.464528e-10   0.500      1.743016e-10   -0.420      2.331301e-10
rho_He4                         3.666324e+20   0.097      3.429012e+20   0.356      2.679088e+20
rho_C12                         4.071438e+16   0.182      3.590071e+16   0.525      2.495741e+16
rho_O16                          1.05492e+17   0.141      9.568069e+16   0.432      7.094558e+16
rho_Cr48                         8.47882e+20   0.015      8.393246e+20   0.163      7.498663e+20
rho_Fe52                        1.583879e+21   -0.012      1.597035e+21   0.095       1.49522e+21
rho_Fe54                        2.136375e+21   0.048      2.066103e+21   0.150      1.861735e+21
rho_Ni56                        4.299942e+21   -0.052      4.458709e+21   0.101      4.157481e+21
rho_Ye                          1.308696e+20   0.421      9.776335e+19   -0.253      1.164792e+20
rho_abar                        3.638818e+23   0.005      3.626128e+23   0.212      3.131245e+23
rho_bea                         1.771828e+21   -0.053      1.837548e+21   0.130      1.679769e+21
rho_enuc                        2.582994e+43   -1.170      5.812759e+43   -0.782      9.997086e+43
```

and with this PR:

```
density                          6.51713e+18   1.835      1.826655e+18   1.477       6.56172e+17
xmom                            3.319164e+27   1.722      1.006337e+27   1.547      3.443109e+26
ymom                            3.319164e+27   1.722      1.006337e+27   1.547      3.443109e+26
rho_E                            8.89183e+36   1.744      2.654286e+36   1.378      1.021286e+36
rho_e                           8.792305e+36   1.744      2.625556e+36   1.375      1.012093e+36
Temp                            1.651966e+20   1.697      5.096478e+19   1.433      1.887716e+19
rho_H1                          6.517171e-12   1.835      1.826649e-12   1.477       6.56169e-13
rho_He4                         9.498165e+17   1.751      2.821303e+17   1.580      9.436239e+16
rho_C12                         3.157079e+13   1.770      9.255075e+12   1.606      3.039383e+12
rho_O16                         8.219515e+13   1.656      2.607704e+13   1.442       9.59849e+12
rho_Cr48                        4.721132e+18   1.875      1.286937e+18   1.568      4.339238e+17
rho_Fe52                        1.588635e+19   1.746      4.737631e+18   1.583      1.581571e+18
rho_Fe54                        8.376093e+19   2.103      1.950261e+19   1.891      5.259356e+18
rho_Ni56                        8.798693e+19   2.022      2.165804e+19   1.744      6.465305e+18
rho_Ye                          3.926305e+18   1.844      1.093468e+18   1.573      3.676152e+17
rho_abar                        1.056123e+21   1.405      3.988732e+20   1.175      1.767009e+20
rho_bea                         6.467178e+19   1.883      1.752888e+19   1.525      6.092063e+18
rho_enuc                        6.910829e+38   0.978      3.508317e+38   0.991      1.764526e+38
```

**Comment by zingale** [comment]
here's the massive_star run with this PR on Summit 

```
Castro       git describe: 23.03-15-g8309823c4
AMReX        git describe: 23.03-23-g7aad6ca7f
Microphysics git describe: 23.03-48-g2679c150-dirty
```

(the `dirty` is just a fix for a CUDA print)

vel_plt21543_slice
comp_plt21543_slice

**Comment by zingale** [comment]
The massive star run there is on 66 GPUs (11 nodes)

**Review by aisclark91 — APPROVED** [review]

**Pull request merged**
