### PR TITLE
Use amu instead of 1/n_A for m_nucleon in gamma_law

### PR DESCRIPTION
**Pull request by psharda**
Is this what we'd want to do (for gamma_law)?

### CODE REVIEW

**Comment by psharda** [comment]
> I'm fine with this, but I want to run it though our suites, since there will be a lot of small changes. But I think it is a good idea to sync up with the standard constants here.

Sounds good. We may also need to update the reference solution for the test that fails.

**Comment by zingale** [comment]
Castro tests:
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2023-07-03-001/index.html

**Comment by BenWibking** [comment]
This looks good to me. @zingale do we need to update the reference solution for the `eos_cell` test? If so, how do we do that?

**Comment by zingale** [comment]
sorry, I will do that.  I'll try to get this done today and do a PR to your PR

**Comment by zingale** [comment]
There's a PR to @psharda 's PR, that once merged will fix the EOS test.  Then this is good to merge.

**Comment by BenWibking** [comment]
> There's a PR to @psharda 's PR, that once merged will fix the EOS test. Then this is good to merge.

@zingale just wanted to check- did this PR get merged?

**Comment by zingale** [comment]
@psharda said that you were trying to understand something before merging this
is it all good now?

**Review by BenWibking — APPROVED** [review]
Looks good to me.

**Review by BenWibking — APPROVED** [review]

**Comment by BenWibking** [comment]
@zingale are you happy with this in its current form? It's ready to go on our end.

**Pull request merged**
