### PR TITLE
extract some common integrator infrastructure

### PR DESCRIPTION
**Pull request by zingale**

### CODE REVIEW

**Comment by zingale** [comment]
this looks a bit clumsy, so comments welcomed.  With this, I can make `BackwardEuler` and `RKC` reuse the same `integrator_setup`

**Comment by zingale** [comment]
update: `std::function()` doesn't work on the device, but a simple function pointer does.

**Comment by zingale** [comment]
it appears that function points are not supported by SYCL, so we'll need to use functors (e.g., a struct wrapper with an overload of ())

**Comment by zingale** [comment]
requires #1541

**Comment by zingale** [comment]
this has been refactored so it will be SYCL compliant now

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
