### PR TITLE
CMake: do not generate network_properties twice

### PR DESCRIPTION
**Pull request by psharda**
We were generating `network_properties.H` for primordial chem twice. 

Also changed AMReX related variable names to use lowercase 'e'

### CODE REVIEW

**Comment by psharda** [comment]
Hmm, why would the docs build be failing?

**Comment by BenWibking** [comment]
It looks like the docs build was broken by a Python upgrade maybe?

**Comment by BenWibking** [comment]
Ok, docs are fixed now.

**Review by BenWibking — APPROVED** [review]

**Comment by BenWibking** [comment]
@zingale since this is a pretty small change that shouldn't affect anything other than the CMake build, I'm going to go ahead and merge unless you have objections.

**Pull request merged**
