### PR TITLE
put species at the start of the simplified-SDC vector

### PR DESCRIPTION
**Pull request by zingale**
this makes the ordering match that of Strang

### CODE REVIEW

**Comment by zingale** [comment]
this causes diffs in the tests -- perhaps because now the matrix is in a different order the linear algebra is different?  Here's the diffs from `test_sdc` with aprox13:

```
fcompare.gnu.ex react_aprox13_sdc_test_react.VODE.cxx react_aprox13_sdc_test_react.VODE.cxx.development

            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 temperature                                      0                         0
 Xnew_helium-4                      1.248502768e-07           1.692646172e-07
 Xnew_carbon-12                     7.685621328e-08           1.097436969e-07
 Xnew_oxygen-16                     6.276688015e-08           8.932614887e-08
 Xnew_neon-20                       1.328537564e-09           1.389993717e-08
 Xnew_magnesium-24                  4.444480881e-09           4.152557998e-08
 Xnew_silicon-28                    2.330433781e-07           4.129795874e-07
 Xnew_sulfur-32                     5.143326721e-08           1.782446034e-07
 Xnew_argon-36                      5.577836631e-08           4.037465731e-07
 Xnew_calcium-40                    6.336522695e-08           1.202182059e-07
 Xnew_titanium-44                   3.068394728e-09           2.839682832e-08
 Xnew_chromium-48                   5.643060533e-09           5.067003127e-08
 Xnew_iron-52                       1.800644849e-08           8.904970088e-08
 Xnew_nickel-56                     2.017725299e-07           2.672618015e-07
 Xold_helium-4                                    0                         0
 Xold_carbon-12                                   0                         0
 Xold_oxygen-16                                   0                         0
 Xold_neon-20                                     0                         0
 Xold_magnesium-24                                0                         0
 Xold_silicon-28                                  0                         0
 Xold_sulfur-32                                   0                         0
 Xold_argon-36                                    0                         0
 Xold_calcium-40                                  0                         0
 Xold_titanium-44                                 0                         0
 Xold_chromium-48                                 0                         0
 Xold_iron-52                                     0                         0
 Xold_nickel-56                                   0                         0
 wdot_helium-4                          3656420.844           1.079999007e-07
 wdot_carbon-12                         2250845.313           3.216418593e-08
 wdot_oxygen-16                         3943556.656           5.639740163e-08
 wdot_neon-20                            71896.4043           1.198403489e-08
 wdot_magnesium-24                       317482.858           5.359351113e-08
 wdot_silicon-28                        23304337.81           4.752842861e-07
 wdot_sulfur-32                         4145971.998           1.552772549e-07
 wdot_argon-36                          5577836.632           6.165684771e-07
 wdot_calcium-40                        6336522.695           8.583217887e-07
 wdot_titanium-44                       166052.1724           2.819518636e-08
 wdot_chromium-48                       343414.3435           6.177562352e-08
 wdot_iron-52                           1329358.048           2.933958588e-07
 wdot_nickel-56                           9440425.5           2.896685867e-07
 rho_Hnuc                           1.581473998e+24           2.456547729e-08
```

**Comment by zingale** [comment]
Here';s what I get with `triple_alpha_plus_cago`:

```
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 temperature                                      0                         0
 Xnew_helium-4                      1.829090213e-10           2.612986018e-10
 Xnew_carbon-12                     1.837764801e-10           2.624122134e-10
 Xnew_oxygen-16                     1.370579206e-10           1.644668614e-10
 Xnew_iron-56                        1.32435729e-12           2.207262151e-12
 Xold_helium-4                                    0                         0
 Xold_carbon-12                                   0                         0
 Xold_oxygen-16                                   0                         0
 Xold_iron-56                                     0                         0
 wdot_helium-4                           18290.8999            1.82908999e-09
 wdot_carbon-12                         18377.64844           6.125905637e-10
 wdot_oxygen-16                         13705.78906           3.426456841e-10
 wdot_iron-56                           132.4340701               1.398560132
 rho_Hnuc                           1.067415346e+22           6.178756076e-10
```

Note that the iron-56 is kinda meaningless, since we don't evolve that, so it's all roundoff

**Comment by zingale** [comment]
here's the test suite run:
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2022-02-28-002/index.html

**Comment by zingale** [comment]
I'll double check that we get the expect convergence from SDC with this change

**Comment by zingale** [comment]
The SDC convergence is identical to the previous ordering:

```
 density                         2.783876e+18   2.048      6.733635e+17   2.558      1.143157e+17
 xmom                            6.779154e+26   2.447      1.242871e+26   2.895      1.671129e+25
 ymom                            6.779154e+26   2.447      1.242871e+26   2.895      1.671129e+25
 rho_E                           2.449619e+35   2.353      4.795335e+34   2.737       7.19335e+33
 rho_e                           2.256441e+35   2.320      4.518365e+34   2.817      6.413752e+33
 Temp                             2.23208e+21   1.695      6.893111e+20   2.484      1.232506e+20
 rho_He4                         2.865944e+18   2.024        7.0489e+17   2.534      1.216822e+17
 rho_C12                         1.694517e+17   1.959      4.357008e+16   2.236      9.250283e+15
 rho_O16                         1.681287e+14   1.662      5.312834e+13   1.963      1.362989e+13
 rho_Fe56                           278386800   2.048          67336340   2.558          11431570```

**Comment by zingale** [comment]
Here's the nse_test convergence with SDC:

```
 $\rho$                          4.499538e+19   1.633      1.450717e+19   1.582      4.844631e+18
 $\rho u$                        1.923207e+28   1.649      6.133238e+27   1.511      2.152448e+27
 $\rho v$                        1.923207e+28   1.649      6.133238e+27   1.511      2.152448e+27
 $\rho E$                        5.605443e+37   1.618      1.826624e+37   1.560      6.195713e+36
 $\rho e$                        5.603818e+37   1.618      1.826272e+37   1.560      6.193922e+36
 $T$                             5.776245e+20   1.740      1.729167e+20   1.703      5.312147e+19
 $\rho X(\isotm{H}{1})$          4.499537e-11   1.633      1.450717e-11   1.582      4.844611e-12
 $\rho X(\isotm{He}{4})$         2.542092e+17   1.807      7.264979e+16   1.635      2.339529e+16
 $\rho X(\isotm{C}{12})$         1.140639e+12   1.838      3.190208e+11   1.670      1.002268e+11
 $\rho X(\isotm{O}{16})$          5.41559e+12   1.819      1.535236e+12   1.658      4.864301e+11
 $\rho X(\isotm{Cr}{48})$        7.023122e+18   1.793      2.027306e+18   1.614      6.621519e+17
 $\rho X(\isotm{Fe}{52})$        3.629021e+19   1.578      1.215164e+19   1.597      4.016465e+18
 $\rho X(\isotm{Fe}{54})$        4.671365e+20   1.807       1.33506e+20   1.869      3.654103e+19
 $\rho X(\isotm{Ni}{56})$        4.852382e+20   1.808      1.385904e+20   1.860      3.816591e+19
 $\rho Y_e$                      2.340355e+19   1.645      7.484097e+18   1.586       2.49213e+18
 $\rho \bar{A}$                  3.984931e+21   1.693       1.23279e+21   1.690      3.819895e+20
 $\rho (B/A)$                    4.178854e+20   1.664      1.318469e+20   1.605       4.33431e+19
```

**Comment by zingale** [comment]
those numbers are as expected

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
