### PR TITLE
add an option to ignore checking the timescale of the rate for NSE_NET

### PR DESCRIPTION
**Pull request by zhichen3**
add an option to ignore the check where we want the time scale of the rates to be smaller than the sound crossing time scale.

### CODE REVIEW

**Comment by zingale** [comment]
is there a reason to compile this out?

**Comment by zhichen3** [comment]
I think I changed it to a run-time option

**Comment by zingale** [comment]
this also seems to have changed something in the fast rate section?

**Review by zingale — APPROVED** [review]

**Comment by zhichen3** [comment]
oh, I uncommented one of the conditions in `find_fast_reaction_cycle`. That condition wasn't specifically mentioned in the paper but was sort of implied. So I commented it out before.

**Pull request merged**
