### PR TITLE
[WIP] improve Strang + NSE coupling

### PR DESCRIPTION
**Pull request by zingale**
This adds an EOS call to get the new T after adding in the energy generation.

### CODE REVIEW

**Comment by zingale** [comment]
with 3 iterations in the loop:

```
 density                         5.572948e+18   1.282      2.291489e+18   1.100      1.069162e+18
 xmom                            1.996623e+27   1.437      7.374591e+26   0.960      3.791496e+26
 ymom                            1.996623e+27   1.437      7.374591e+26   0.960      3.791496e+26
 rho_E                           1.209202e+37   1.370      4.677986e+36   1.184      2.059518e+36
 rho_e                           1.209062e+37   1.370      4.677399e+36   1.184      2.059272e+36
 Temp                            6.254342e+19   1.095      2.927344e+19   1.028      1.435304e+19
 rho_H1                          5.572942e-12   1.282        2.2915e-12   1.100      1.069164e-12
 rho_He4                         3.447345e+17   1.253      1.446502e+17   1.146      6.534417e+16
 rho_C12                         1.184662e+13   1.411      4.453737e+12   1.184      1.960583e+12
 rho_O16                         4.055898e+13   1.293      1.655673e+13   1.132      7.553974e+12
 rho_Cr48                        2.423799e+18   1.453      8.853901e+17   1.291      3.619243e+17
 rho_Fe52                        6.605606e+18   1.338      2.613551e+18   1.139      1.186344e+18
 rho_Fe54                        4.109216e+19   1.765       1.20921e+19   1.622      3.929323e+18
 rho_Ni56                        4.771091e+19   1.619      1.553524e+19   1.454      5.672264e+18
 rho_Ye                          3.240902e+18   1.400      1.227886e+18   1.186      5.396704e+17
 rho_abar                        8.503891e+20   1.120       3.91257e+20   1.067      1.867774e+20
 rho_bea                         4.823953e+19   1.268       2.00351e+19   1.110      9.281064e+18
 rho_enuc                        9.001301e+39   0.888      4.862575e+39   0.945      2.526627e+39```

**Comment by aisclark91** [comment]
with 15 iterations:

```
density        4.723691e+18       1.581852   1.577962e+18
xmom        2.363538e+27       1.821300   6.688004e+26
ymom        2.363538e+27       1.821300   6.688004e+26
zmom        0.000000e+00   ------------   0.000000e+00
rho_E        9.960052e+36       1.516512   3.481336e+36
rho_e        9.959130e+36       1.516554   3.480913e+36
Temp        1.234129e+20       1.134391   5.621792e+19
rho_H1        4.723674e-12       1.581845   1.577965e-12
rho_He3        2.244750e+10       1.608105   7.363427e+09
rho_He4        4.049882e+17       1.149379   1.825765e+17
rho_C12        1.292474e+13       1.343912   5.091712e+12
rho_N14        4.723674e-12       1.581845   1.577965e-12
rho_O16        4.793540e+13       1.208357   2.074458e+13
rho_Ne20        1.355728e+12       1.308282   5.474448e+11
rho_Mg24        3.973985e+14       1.105696   1.846624e+14
rho_Si28        3.892649e+17       1.076053   1.846380e+17
rho_S32        6.694059e+17       1.092316   3.139566e+17
rho_Ar36        6.554670e+17       1.101998   3.053631e+17
rho_Ca40        1.209779e+18       1.147690   5.460308e+17
rho_Ti44        1.227423e+17       1.109323   5.689247e+16
rho_Cr48        2.474444e+18       1.300642   1.004489e+18
rho_Fe52        1.099240e+19       1.264152   4.576622e+18
rho_Fe54        3.940367e+19       1.697313   1.215051e+19
rho_Ni56        4.652798e+19       1.483117   1.664376e+19
rho_n        1.262549e+13       1.905375   3.370335e+12
rho_p        4.611926e+17       1.171368   2.047696e+17
rho_Ye        2.842941e+18       1.666710   8.954436e+17
rho_abar        1.359159e+21       1.132129   6.201054e+20
rho_bea        3.907820e+19       1.538116   1.345599e+19
rho_enuc        7.295733e+38       1.026589   3.581253e+38
```

**Comment by zhichen3** [comment]
If we do more iterations, shouldn't we make `dt` during each iteration smaller so that we are advancing by `dt` in total? e.g. if 3 iterations then `dt/3.0` or 4 iterations `0.25*dt`? 

If I do that, I get:
```
 density                         5.349384e+18   1.356      2.089934e+18   1.136      9.510745e+17
 xmom                            2.047607e+27   1.553      6.977023e+26   1.040       3.39212e+26
 ymom                            2.047607e+27   1.553      6.977023e+26   1.040       3.39212e+26
 rho_E                           1.136543e+37   1.424      4.235887e+36   1.219      1.820179e+36
 rho_e                           1.136407e+37   1.424      4.235357e+36   1.219      1.819979e+36
 Temp                            6.694465e+19   1.048      3.238816e+19   1.004       1.61517e+19
 rho_H1                          5.349345e-12   1.356      2.089931e-12   1.136      9.510751e-13
 rho_He4                         3.502008e+17   1.260      1.462193e+17   1.165      6.521368e+16
 rho_C12                         1.115267e+13   1.419      4.171354e+12   1.241      1.765155e+12
 rho_O16                         3.815082e+13   1.284       1.56658e+13   1.180      6.915291e+12
 rho_Cr48                         2.54969e+18   1.454      9.309582e+17   1.291       3.80389e+17
 rho_Fe52                        7.562117e+18   1.301      3.069159e+18   1.147      1.385618e+18
 rho_Fe54                        4.441139e+19   1.732      1.336629e+19   1.598      4.416311e+18
 rho_Ni56                        5.122476e+19   1.593      1.698213e+19   1.430      6.304428e+18
 rho_Ye                          3.156392e+18   1.470      1.139692e+18   1.235      4.842617e+17
 rho_abar                        8.736528e+20   1.094       4.09172e+20   1.054      1.970738e+20
 rho_bea                         4.579011e+19   1.336      1.813754e+19   1.141      8.225961e+18
 rho_enuc                        5.550567e+39   0.954      2.864243e+39   0.974      1.458268e+39

```
which is slightly better I guess

**Comment by zhichen3** [comment]
I was also thinking it is also reasonable to limit `deltaq` for each iteration. e.g. if doing 2 iterations then `Real deltaq = 0.5_rt * (dq_out - bea_in);` and after we update `state.aux[ibea]=bea_in + deltaq`, we also update `bea_in`, by setting `bea_in=state.aux[ibea]`.

With 2 iterations and this idea, I have:

```
 density                         3.812498e+18   1.849      1.058224e+18   1.592      3.509047e+17
 xmom                            2.726247e+27   1.830      7.666088e+26   1.746      2.285794e+26
 ymom                            2.726247e+27   1.830      7.666088e+26   1.746      2.285794e+26
 rho_E                           7.710705e+36   1.901       2.06502e+36   1.635        6.6468e+35
 rho_e                           7.710013e+36   1.901      2.064718e+36   1.635      6.645626e+35
 Temp                            5.457218e+19   1.377      2.100892e+19   1.240       8.89467e+18
 rho_H1                          3.812459e-12   1.849      1.058224e-12   1.592      3.509047e-13
 rho_He4                         3.679909e+17   1.065      1.758853e+17   0.937      9.189674e+16
 rho_C12                         9.795814e+12   1.393       3.73049e+12   0.954      1.925016e+12
 rho_O16                         3.683993e+13   1.133      1.679768e+13   0.933       8.79639e+12
 rho_Cr48                        2.416314e+18   1.104      1.124017e+18   1.005      5.600699e+17
 rho_Fe52                        1.358111e+19   1.209      5.875043e+18   1.115       2.71298e+18
 rho_Fe54                        3.901793e+19   1.695      1.205422e+19   1.413      4.527715e+18
 rho_Ni56                        4.644613e+19   1.416      1.740233e+19   1.091      8.170046e+18
 rho_Ye                          2.402896e+18   1.914      6.377053e+17   1.684      1.984402e+17
 rho_abar                        1.457778e+21   1.068      6.954968e+20   0.994       3.49232e+20
 rho_bea                         3.120435e+19   1.811      8.891506e+18   1.521      3.098331e+18
 rho_enuc                        2.437748e+37   1.071      1.160041e+37   0.928      6.098857e+36
```

**Comment by zhichen3** [comment]
With 4 iterations (`Real deltaq = 0.25_rt * (dq_out - bea_in)` and `0.25*dt` for ye update), we have:

```
 density                         3.960973e+18   1.859      1.091949e+18   1.610      3.576447e+17
 xmom                            2.640178e+27   1.867       7.23813e+26   1.774      2.117129e+26
 ymom                            2.640178e+27   1.867       7.23813e+26   1.774      2.117129e+26
 rho_E                           7.987988e+36   1.900      2.139921e+36   1.658      6.780953e+35
 rho_e                           7.987253e+36   1.900      2.139591e+36   1.658      6.779495e+35
 Temp                            3.177257e+19   1.848      8.823372e+18   1.685      2.744406e+18
 rho_H1                          3.960965e-12   1.859      1.091943e-12   1.610      3.576424e-13
 rho_He4                         1.291741e+17   1.850      3.582887e+16   1.682      1.116987e+16
 rho_C12                         5.752089e+12   1.906      1.535181e+12   1.792      4.431935e+11
 rho_O16                         1.523654e+13   1.824       4.30419e+12   1.713      1.313121e+12
 rho_Cr48                        1.435693e+18   1.969      3.666574e+17   1.898      9.841213e+16
 rho_Fe52                        4.400392e+18   1.786      1.275887e+18   1.668      4.015446e+17
 rho_Fe54                        3.671761e+19   1.983      9.291077e+18   1.988      2.342393e+18
 rho_Ni56                        3.702575e+19   1.973      9.431238e+18   1.950      2.441319e+18
 rho_Ye                           2.50505e+18   1.909      6.670871e+17   1.708      2.041558e+17
 rho_abar                        4.389709e+20   1.755      1.300547e+20   1.589      4.322627e+19
 rho_bea                         3.215152e+19   1.838      8.995122e+18   1.585      2.998626e+18
 rho_enuc                         1.06011e+38   0.982      5.367894e+37   0.925      2.827581e+37
```

**Comment by zingale** [comment]
okay, I've updated the PR to take a parameter `nse_substeps` which defaults to 4.  It doesn't do exactly what Zhi's changes did, since  I don't think all of the Ye and energy were added there, but it gets reasonable convergence.

I want to focus on making this work with self-consistent NSE now so we can merge it and continue to experiment.

**Comment by zingale** [comment]
closing this -- we should adapt the strategy in #1392 later

**Pull request closed without merging**
