### PR TITLE
Mark some variables maybe_unused in Helmholtz

### PR DESCRIPTION
**Pull request by maxpkatz**
This attribute (from C++17) quiets unused variable compiler warnings.

### CODE REVIEW

**Comment by zingale** [comment]
maybe we should replace ``MICROPHYSICS_UNUSED`` then?

**Comment by zingale** [comment]
did we decide if we were going to do this via MICROPHYSICS_UNUSED? or should I just merge?

**Comment by maxpkatz** [comment]
Yes, I agree that we should do it via MICROPHYSICS_UNUSED, so please hold for now until I make that change.

**Comment by maxpkatz** [comment]
I changed my mind on the above, we should try to use the C++ standard syntax, and only drop back to using the macro if we run into a compiler that doesn't support this. So we should merge. I'll deal with MICROPHYSICS_UNUSED some other time.

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2022-04-30/index.html

**Pull request merged**
