### PR TITLE
get the BackwardEuler solver working with simplified-SDC

### PR DESCRIPTION
**Pull request by zingale**

### CODE REVIEW

**Comment by zingale** [comment]
builds on #1041

**Comment by zingale** [comment]
depends on #1043

**Comment by zingale** [comment]
current status: simplified-SDC builds with `BackwardEuler`, but the `burn_cell_sdc` test fails with too many steps

**Comment by zingale** [comment]
this works now

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
