### PR TITLE
add neutrino loses to NSE table with SDC

### PR DESCRIPTION
**Pull request by zingale**

### CODE REVIEW

**Comment by zhichen3** [comment]
I decided to run convergence test with nse_net and sdc for this pr, I get lower energy convergence
```
 density                         9.567319e+18   1.858      2.639481e+18   1.999      6.602678e+17
 xmom                            5.271134e+27   1.943      1.371157e+27   1.952      3.544106e+26
 ymom                            5.271134e+27   1.943      1.371157e+27   1.952      3.544106e+26
 rho_E                           1.777975e+37   1.874      4.848941e+36   2.001      1.211506e+36
 rho_e                           1.777955e+37   1.874      4.849097e+36   2.001      1.211556e+36
 Temp                            4.109141e+19   1.967      1.051007e+19   1.998      2.630733e+18
 rho_H1                          1.123645e+15   1.979      2.850569e+14   2.000      7.125031e+13
 rho_He4                         1.125177e+17   1.977      2.857903e+16   1.995      7.167317e+15
 rho_C12                         2.044676e+12   1.989      5.150941e+11   1.999      1.288713e+11
 rho_O16                         5.803872e+12   1.982      1.468942e+12   1.993      3.688951e+11
 rho_Cr48                        1.972718e+17   1.937       5.15158e+16   1.987      1.299478e+16
 rho_Fe52                        3.113604e+18   1.932      8.160043e+17   1.995      2.047527e+17
 rho_Ni56                         4.48484e+19   1.981      1.136216e+19   2.002      2.836802e+18
 rho_enuc                        2.887078e+35   0.999         1.445e+35   1.006       7.19573e+34
```

vs. before:

```
 density                         9.286321e+18   1.843      2.587988e+18   1.990      6.515428e+17
 xmom                            5.319227e+27   1.987      1.341661e+27   1.947       3.47999e+26
 ymom                            5.319227e+27   1.987      1.341661e+27   1.947       3.47999e+26
 rho_E                           1.720004e+37   1.857      4.748071e+36   1.993      1.192921e+36
 rho_e                            1.71995e+37   1.857      4.748131e+36   1.993      1.192941e+36
 Temp                            4.043189e+19   1.963      1.037037e+19   1.991      2.608408e+18
 rho_H1                          1.119004e+15   1.979      2.839123e+14   2.001      7.094477e+13
 rho_He4                          1.10357e+17   2.011      2.738473e+16   2.062      6.557745e+15
 rho_C12                         2.020089e+12   2.043      4.902361e+11   2.075      1.163277e+11
 rho_O16                         5.765372e+12   2.020      1.421683e+12   2.048      3.438919e+11
 rho_Cr48                        1.917702e+17   1.935      5.016802e+16   1.985      1.267326e+16
 rho_Fe52                        3.044508e+18   1.929      7.995788e+17   1.993       2.00917e+17
 rho_Ni56                        4.478907e+19   1.978      1.137299e+19   2.001      2.841874e+18
 rho_enuc                        1.505582e+38   1.459      5.476177e+37   1.358       2.13694e+37
```

Is this expected?

**Comment by zingale** [comment]
That's interesting.  To be honest, I don't understand the energy convergence yet.  I'm struggling with that with the tabular stuff.

**Comment by zhichen3** [comment]
> That's interesting. To be honest, I don't understand the energy convergence yet. I'm struggling with that with the tabular stuff.

do you observe the same thing (lower convergence) with tabular nse?

**Comment by zingale** [comment]
I am not sure.  I need to rerun to see what happens with the old version.

**Comment by zingale** [comment]
I don't see much difference when I remove the neutrino stuff with the table.

It's possible that with the self-consistent NSE that I am not time-centering things correctly.

**Comment by zingale** [comment]
I think that this convergence is fine.  We would expect the integral quantities to converge as second order, but rho_enuc is a derivative, which means we divide by dt, so we lose an order of convergence there.  I think that the diffs here result from the enuc term being larger in this PR -- note the size of the norm.

**Review by zhichen3 — APPROVED** [review]

**Pull request merged**
