### PR TITLE
add a compiler warning action

### PR DESCRIPTION
**Pull request by zingale**
this is based on Castro and will fail if we generate warnings

### CODE REVIEW

**Comment by zingale** [comment]
implements #1184

**Comment by BenWibking** [comment]
What compiler does the CI use? With gcc 11.3.1, I'm seeing warnings in `integration/VODE/actual_integrator.H`:
```
[ 42%] Building CXX object src/PrimordialChem/CMakeFiles/test_primordial_chem.dir/__/Chemistry.cpp.o
In file included from /home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/integrator.H:7,
                 from /home/opc/azure-pipelines/_work/1/s/extern/Microphysics/interfaces/burner.H:5,
                 from /home/opc/azure-pipelines/_work/1/s/src/Chemistry.cpp:12:
In function ‘void actual_integrator(burn_t&, amrex::Real)’,
    inlined from ‘void integrator(burn_t&, amrex::Real)’ at /home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/integrator.H:13:22,
    inlined from ‘void burner(burn_t&, amrex::Real)’ at /home/opc/azure-pipelines/_work/1/s/extern/Microphysics/interfaces/burner.H:86:15,
    inlined from ‘void quokka::chemistry::chemburner(burn_t&, amrex::Real)’ at /home/opc/azure-pipelines/_work/1/s/src/Chemistry.cpp:17:76:
/home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/VODE/actual_integrator.H:102:30: error: ‘vode_state’ may be used uninitialized [-Werror=maybe-uninitialized]
  102 |     state.n_rhs = vode_state.NFE;
      |                   ~~~~~~~~~~~^~~
/home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/VODE/actual_integrator.H: In function ‘void quokka::chemistry::chemburner(burn_t&, amrex::Real)’:
/home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/VODE/actual_integrator.H:20:13: note: ‘vode_state’ declared here
   20 |     dvode_t vode_state;
      |             ^~~~~~~~~~
In function ‘void actual_integrator(burn_t&, amrex::Real)’,
    inlined from ‘void integrator(burn_t&, amrex::Real)’ at /home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/integrator.H:13:22,
    inlined from ‘void burner(burn_t&, amrex::Real)’ at /home/opc/azure-pipelines/_work/1/s/extern/Microphysics/interfaces/burner.H:86:15,
    inlined from ‘void quokka::chemistry::chemburner(burn_t&, amrex::Real)’ at /home/opc/azure-pipelines/_work/1/s/src/Chemistry.cpp:17:76:
/home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/VODE/actual_integrator.H:104:31: error: ‘vode_state.dvode_t::NST’ may be used uninitialized [-Werror=maybe-uninitialized]
  104 |     state.n_step = vode_state.NST;
      |                    ~~~~~~~~~~~^~~
/home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/VODE/actual_integrator.H: In function ‘void quokka::chemistry::chemburner(burn_t&, amrex::Real)’:
/home/opc/azure-pipelines/_work/1/s/extern/Microphysics/integration/VODE/actual_integrator.H:20:13: note: ‘vode_state’ declared here
   20 |     dvode_t vode_state;
      |             ^~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Or maybe this code path is not getting triggered elsewhere?

**Comment by BenWibking** [comment]
I think the issue is that gcc produces additional warnings when building in release mode (?!). Does this build successfully if you set `DEBUG=FALSE`?

**Comment by zingale** [comment]
I use GCC 13.1 locally.  Not sure what it pulls down in the CI.

For the GNUmake stuff in AMReX, the warnings are only turned on if `WARN_ALL=TRUE`, which I do here.  This is what they add:

```
warning_flags = -Wall -Wextra -Wlogical-op -Wfloat-conversion -Wnull-dereference -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wmissing-include-dirs
```

The uninitialized check is turned on with `DEBUG=TRUE` in `gnu.mak`.

**Comment by zingale** [comment]
oh, but this is `maybe-uninitialized`, so we should add that.  Maybe we need to do a PR to AMReX

**Comment by zingale** [comment]
ah, indeed, that only works for optimized compiling.  So it looks like we should check with both `DEBUG=TRUE` and `DEBUG=FALSE`.  I'll try that now.

**Comment by BenWibking** [comment]
Ok, that explains it. I also turn on `-Wextra`, which adds `-Wuninitialized` (https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-W). But I still only get the warning with optimizations on, which is a bit worrying.

**Comment by BenWibking** [comment]
It looks like changing
```
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE
void actual_integrator (burn_t& state, Real dt)
{
    dvode_t vode_state;
```
to
```
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE
void actual_integrator (burn_t& state, Real dt)
{
    dvode_t vode_state{};
```
fixed it for me.

**Comment by zingale** [comment]
okay, I've added compiler warning tests w/o debug too.  Let's see how those fail, then I'll fix it up.

**Comment by BenWibking** [comment]
is anything else needed to merge this? I'm eager to update Quokka with these fixes.

**Review by BenWibking — APPROVED** [review]

**Pull request merged**
