### PR TITLE
Revamp CMake to enable building Microphysics as a submodule with different EOS

### PR DESCRIPTION
**Pull request by psharda**
@ben and I are planning to completely remove EOS from Quokka and use Microphysics for all EOS calculations. In order to do this, we require Microphysics be built not only for primordial chem, but for all Quokka tests. All the current Quokka tests use a single-gamma EOS whereas primordial chem uses an implementation of multigamma. So, we need to build Microphysics with different EOS for different Quokka tests.

This PR is the first step towards enabling multi EOS support for Microphysics when we build it as a submodule within Quokka using CMake.

### CODE REVIEW

**Comment by psharda** [comment]
Just FYI this PR is still under progress. I will send an update when it's ready for review.

**Comment by BenWibking** [comment]
I think you @'ed the wrong Ben...

We should get rid of the old `add_library` stuff, since we're aren't attempting to build Microphysics as a shared library anymore. It also causes the build to fail on Setonix (for some reason I don't understand).

**Comment by psharda** [comment]
Okay. How do I build Microphysics as a target if not using `add_library`? If I comment out the `add_library` line, I also need to comment out:

```
target_sources(Microphysics PUBLIC ${sources})
target_compile_definitions(Microphysics PUBLIC NAUX_NET STRANG)
```
which is fine because I don't think we need the sources, and I can add the compile definitions directly to the primordial chem test target in `Microphysics/unit_test/burn_cell_primordial_chem`

But, what do I do with this part:

```
set_target_properties(Microphysics PROPERTIES
    SOVERSION ${PROJECT_VERSION_MAJOR}
    VERSION ${PROJECT_VERSION}
    LINKER_LANGUAGE CXX)

```

Commenting this out generates errors...

**Comment by BenWibking** [comment]
That's odd. I commented all of this out locally and built it. What error are you getting?

**Comment by psharda** [comment]
Just making sure you use `cmake .. -DBUILD_UNIT_TEST=true _DBUILD_AMREX=true` ?

When I do `make`, I get these errors:

```
[ 99%] Building CXX object unit_test/burn_cell_primordial_chem/CMakeFiles/test_burn_cell_primordial_chem.dir/__/__/extern_parameters.cpp.o
In file included from /Users/psharda/Documents/Microphysics/EOS/primordial_chem/actual_eos_data.cpp:1:
In file included from /Users/psharda/Documents/Microphysics/EOS/primordial_chem/actual_eos_data.H:6:
In file included from /Users/psharda/Documents/Microphysics/interfaces/network.H:5:
/Users/psharda/Documents/Microphysics/build/network_properties.H:33:24: error: use of undeclared identifier 'NAUX_NET'
constexpr int NumAux = NAUX_NET;
                       ^
1 error generated.
make[2]: *** [unit_test/burn_cell_primordial_chem/CMakeFiles/test_burn_cell_primordial_chem.dir/build.make:118: unit_test/burn_cell_primordial_chem/CMakeFiles/test_burn_cell_primordial_chem.dir/__/__/EOS/primordial_chem/actual_eos_data.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/main.cpp:10:
In file included from /Users/psharda/Documents/Microphysics/interfaces/eos.H:4:
/Users/psharda/Documents/Microphysics/build/network_properties.H:33:24: error: use of undeclared identifier 'NAUX_NET'
constexpr int NumAux = NAUX_NET;
                       ^
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/main.cpp:12:
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/burn_cell.H:4:
In file included from /Users/psharda/Documents/Microphysics/interfaces/burner.H:5:
In file included from /Users/psharda/Documents/Microphysics/integration/integrator.H:7:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/actual_integrator.H:14:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/vode_type.H:10:
/Users/psharda/Documents/Microphysics/integration/integrator_data.H:20:34: error: use of undeclared identifier 'INT_NEQS'
typedef amrex::Array1D<short, 1, INT_NEQS> IArray1D;
                                 ^
/Users/psharda/Documents/Microphysics/integration/integrator_data.H:21:33: error: use of undeclared identifier 'INT_NEQS'
typedef amrex::Array1D<Real, 1, INT_NEQS> RArray1D;
                                ^
/Users/psharda/Documents/Microphysics/integration/integrator_data.H:22:35: error: use of undeclared identifier 'INT_NEQS'
typedef ArrayUtil::MathArray2D<1, INT_NEQS, 1, INT_NEQS> RArray2D;
                                  ^
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/main.cpp:12:
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/burn_cell.H:4:
In file included from /Users/psharda/Documents/Microphysics/interfaces/burner.H:5:
In file included from /Users/psharda/Documents/Microphysics/integration/integrator.H:7:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/actual_integrator.H:14:
/Users/psharda/Documents/Microphysics/integration/VODE/vode_type.H:12:23: error: use of undeclared identifier 'INT_NEQS'
const int VODE_NEQS = INT_NEQS;
                      ^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_type.H:230:58: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
        std::cout << "y(" << i << ") = " << dvode_state.y(i) << std::endl;
                                            ~~~~~~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_type.H:240:62: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
        std::cout << "ewt(" << i << ") = " << dvode_state.ewt(i) << std::endl;
                                              ~~~~~~~~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_type.H:244:64: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
        std::cout << "savf(" << i << ") = " << dvode_state.savf(i) << std::endl;
                                               ~~~~~~~~~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_type.H:248:64: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
        std::cout << "acor(" << i << ") = " << dvode_state.acor(i) << std::endl;
                                               ~~~~~~~~~~~~~~~~^
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/main.cpp:12:
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/burn_cell.H:4:
In file included from /Users/psharda/Documents/Microphysics/interfaces/burner.H:5:
In file included from /Users/psharda/Documents/Microphysics/integration/integrator.H:7:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/actual_integrator.H:15:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/vode_dvode.H:5:
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvhin.H:92:25: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
                vstate.y(i) = vstate.yh(i,1) + H * vstate.yh(i,2);
                ~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvhin.H:97:13: error: use of undeclared identifier 'rhs'
            rhs(t1, state, vstate, vstate.acor);
            ^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvhin.H:100:28: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
                vstate.acor(i) = (vstate.acor(i) - vstate.yh(i,2)) / H;
                ~~~~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvhin.H:100:46: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
                vstate.acor(i) = (vstate.acor(i) - vstate.yh(i,2)) / H;
                                  ~~~~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvhin.H:105:39: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
                YDDNRM += (vstate.acor(i) * vstate.ewt(i)) * (vstate.acor(i) * vstate.ewt(i));
                           ~~~~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvhin.H:105:55: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
                YDDNRM += (vstate.acor(i) * vstate.ewt(i)) * (vstate.acor(i) * vstate.ewt(i));
                                            ~~~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvhin.H:105:74: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
                YDDNRM += (vstate.acor(i) * vstate.ewt(i)) * (vstate.acor(i) * vstate.ewt(i));
                                                              ~~~~~~~~~~~^
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvhin.H:105:90: error: called object type 'RArray1D' (aka 'int') is not a function or
      function pointer
                YDDNRM += (vstate.acor(i) * vstate.ewt(i)) * (vstate.acor(i) * vstate.ewt(i));
                                                                               ~~~~~~~~~~^
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/main.cpp:12:
In file included from /Users/psharda/Documents/Microphysics/unit_test/burn_cell_primordial_chem/burn_cell.H:4:
In file included from /Users/psharda/Documents/Microphysics/interfaces/burner.H:5:
In file included from /Users/psharda/Documents/Microphysics/integration/integrator.H:7:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/actual_integrator.H:15:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/vode_dvode.H:6:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/vode_dvstep.H:7:
In file included from /Users/psharda/Documents/Microphysics/integration/VODE/vode_dvnlsd.H:8:
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvjac.H:84:23: error: member reference base type 'RArray2D' (aka 'int') is not a
      structure or union
            vstate.jac.zero();
            ~~~~~~~~~~^~~~~
/Users/psharda/Documents/Microphysics/integration/VODE/vode_dvjac.H:86:13: error: use of undeclared identifier 'jac'
            jac(vstate.tn, state, vstate, vstate.jac);
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [unit_test/burn_cell_primordial_chem/CMakeFiles/test_burn_cell_primordial_chem.dir/build.make:76: unit_test/burn_cell_primordial_chem/CMakeFiles/test_burn_cell_primordial_chem.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1044: unit_test/burn_cell_primordial_chem/CMakeFiles/test_burn_cell_primordial_chem.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by BenWibking** [comment]
Ah, I was building the `primordial_chem` problem in Quokka. Somehow that works...?

**Comment by BenWibking** [comment]
@psharda Just to check, is this PR still a work-in-progress, or was this superceded by your other PR?

**Comment by psharda** [comment]
There are some other changes that I was trying here, but Max's PR supersedes them. So I can close this PR now.

**Comment by psharda** [comment]
Superseded by #1237

**Pull request closed without merging**
