### PR TITLE
Construct some containers for data in rhs.H

### PR DESCRIPTION
**Pull request by maxpkatz**
Containers for state data and rate data are constructed. These significantly clean up interfaces (and therefore make them more extensible in the future) and also help quiet unused variable warnings.

### CODE REVIEW

**Comment by zingale** [comment]
do we expect roundoff diffs?

**Comment by maxpkatz** [comment]
No I wasn't expecting any diffs.

**Comment by maxpkatz** [comment]
But even though the arithmetic operations aren't changing, it's possible the compiler will optimize it differently when we combine data into structs.

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2022-11-20/index.html

aprox21 crashes

**Comment by maxpkatz** [comment]
> tests: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2022-11-20/index.html
> 
> aprox21 crashes

fixed

**Comment by zingale** [comment]
J_helium-3_hydrogen-1 is quite large:
http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2022-11-20-001/test_rhs_aprox19.html

**Comment by zingale** [comment]
tests pass now: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2022-11-20-002/index.html

**Review by zingale — APPROVED** [review]

**Pull request merged**
