### PR TITLE
for simplified-SDC, eliminate a temporary ydot_react array

### PR DESCRIPTION
**Pull request by zingale**
since we have shifted such that the SDC VODE state is in the same
order as Strang, we no longer need a temporary.  This frees up
memory and a potentially expensive copy.

This can give roundoff diffs

### CODE REVIEW

**Comment by zingale** [comment]
Castro tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2022-03-16-008/index.html

**Comment by zingale** [comment]
Microphysics SDC test: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2022-03-16-003/index.html

**Comment by zingale** [comment]
it compounds over the integration to give different final X's:

`development`:

```
species: 
0 0
1 1.503097372e-08
2 32.11510206
3 8.411699596
4 2.37361178e-10
5 497.7531059
6 0.1868184056
7 29.93244685
8 779539.9547
9 501784.4179
10 106856.5509
11 88893.62065
12 95.9719752
13 10839.05856
14 0
15 6050281.46
16 2826990.369
17 0
18 50.52136739
19 4.66970622e+24
20 10365900.32
21 0
22 0
23 0
24 4.682670367e+24
number of RHS calls = 281
```

this PR:

```
species: 
0 0
1 1.696058034e-08
2 32.18231137
3 8.403535999
4 2.297468727e-09
5 497.3547861
6 0.1868163093
7 29.90338534
8 778912.5319
9 501371.0468
10 106766.188
11 88825.38567
12 95.94125958
13 10831.03545
14 0
15 6053782.534
16 2824697.052
17 0
18 50.57826149
19 4.673731502e+24
20 10365900.32
21 0
22 0
23 0
24 4.686695649e+24```

**Comment by zingale** [comment]
actually, there was another bug there.  Now things agree with test_sdc_vode_rhs.

I'm retesting Castro

**Comment by zingale** [comment]
okay, all Castro tests pass now:
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2022-03-22-001/index.html

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
